#### Question 1

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [7]:
import numpy as np

## Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
## an intermediate vector. Use diff order formula based on increasing and decreasing condition.
## Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix. 
   
def vander_matrix(input_vector, n, increasing):
    
    if not increasing:
        output = np.array([x**(n-1-i) for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    elif increasing:
        output = np.array([x**i for x in input_vector for i in range(n)]).reshape(input_vector.size,n)
    
    return output

print("------------OUTPUT-------------\n")

input_vector = np.array([1,2,3,4,5])
n = 3
output_dec_order = vander_matrix(input_vector,n,False)
output_inc_order = vander_matrix(input_vector,n,True)

print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix should be:",n,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_inc_order,"\n")

input_vector = np.array([3,4,5,2,1,8])
n = 4
output_dec_order = vander_matrix(input_vector,n,False)
output_inc_order = vander_matrix(input_vector,n,True)

print("---------------------------------------------------------------\n")
print("The input array is:",input_vector,"\n")
print("Number of columns in output matrix should be:",n,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_inc_order,"\n")

------------OUTPUT-------------

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

---------------------------------------------------------------

The input array is: [3 4 5 2 1 8] 

Number of columns in output matrix should be: 4 

Vander matrix of the input array in decreasing order of powers:

 [[ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [  8   4   2   1]
 [  1   1   1   1]
 [512  64   8   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   2   4   8]
 [  1   1   1   1]
 [  1   8  64 512]] 



#### Question 2 

Problem Statement:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

#### Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.



In [15]:
def moving_average(input_list, k):
    cumsum, moving_aves = [0], []
    for i, x in enumerate(input_list, 1):
        cumsum.append(cumsum[i-1] + x) # summing up all the values one by one and appending the list
        if i>=k:
            moving_ave = round(((cumsum[i] - cumsum[i-k])/k),2) #computing the moving average using temp array sum array cumsum
            #can do stuff with moving_ave here
            moving_aves.append(moving_ave) # listing the moving average as an single array
    
    print("Moving average values list: ", moving_aves)
    print("Length of the list n-k+1: ", len(moving_aves))

In [16]:
#Let's test with the example:

input_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
k = 4
moving_average(input_list,k)

Moving average values list:  [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]
Length of the list n-k+1:  7


In [17]:
#Answering the question

input_list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
k = 3
moving_average(input_list,k)

Moving average values list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list n-k+1:  11
